sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-diff"

before_script:
  - phpize && ./configure && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
